name: build&test

on: push

jobs: 
  build&test-job:

    runs-on: ubuntu-latest

    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: npm run build
      - run: npm test